In [1]:
from IPython.display import display, Math
import sympy as sym
import numpy as np

In [2]:
A = np.array([ [1,2],[3,4] ])

In [3]:
A

array([[1, 2],
       [3, 4]])

In [4]:
type(A)

numpy.ndarray

In [5]:
display( Math( sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>

In [7]:
mat = np.zeros([4,6])

In [8]:
mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
mat[2, 4] = 7

In [12]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
numrange = range(0,4)
for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (-1)**(rowi+coli)
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [15]:
x, y = sym.symbols('x y')

In [21]:
Fxy = (4 + x) * (2 - y)

xyset = range(0, 3)
outmat = np.zeros([len(xyset), len(xyset)])

for i in xyset:
    for j in xyset:        
        outmat[i,j] = Fxy.subs({x: i, y: j})


In [24]:
display( Math( sym.latex(sym.sympify(outmat) ) ) )

<IPython.core.display.Math object>

In [36]:

nums = range(1, 11)
matmul = np.zeros([len(nums), len(nums)], dtype=int)

for rowi in nums:
    for coli in nums:
        #print(f"rowi: {rowi}, coli: {coli}")
        matmul[rowi - 1, coli-1] = rowi * coli

In [37]:
display( Math( sym.latex(sym.sympify( matmul)) ) )

<IPython.core.display.Math object>