In [1]:
import numpy as np
import math
from IPython.display import display, Math
import sympy as sym

In [2]:
math.gcd(6, 15)

3

In [3]:
a = 16
b = 88


a / b

0.18181818181818182

In [4]:
fact = math.gcd(a, b)
print(fact)

8


In [7]:
display( Math( '\\frac{%g}{%g} = \\frac{%g\\times %g}{%g \\times %g}' %(a, b, a/fact, fact, b/fact, fact)))

<IPython.core.display.Math object>

In [8]:
a, b, c = sym.symbols('a, b, c')

In [9]:
sym.gcd(a*c, b*c)

c

In [10]:
sym.gcd(a,b)

1

In [11]:
a = 5
b = 6
c = 7

In [13]:
print(math.gcd(a*c, b*c))

7


In [20]:
n = 10
m = 15

gcdmat = np.zeros([n, m], dtype='int')+99
gcdmat

array([[99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99]])

In [21]:
for rowi in range(0, n):
    for coli in range(0, m):
        gcdmat[rowi, coli] = math.gcd(rowi+1, coli+ 1)

In [22]:
print(gcdmat)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  2  1  2  1  2  1  2  1  2  1  2  1  2  1]
 [ 1  1  3  1  1  3  1  1  3  1  1  3  1  1  3]
 [ 1  2  1  4  1  2  1  4  1  2  1  4  1  2  1]
 [ 1  1  1  1  5  1  1  1  1  5  1  1  1  1  5]
 [ 1  2  3  2  1  6  1  2  3  2  1  6  1  2  3]
 [ 1  1  1  1  1  1  7  1  1  1  1  1  1  7  1]
 [ 1  2  1  4  1  2  1  8  1  2  1  4  1  2  1]
 [ 1  1  3  1  1  3  1  1  9  1  1  3  1  1  3]
 [ 1  2  1  2  5  2  1  2  1 10  1  2  1  2  5]]


In [25]:
display( Math( sym.latex( sym.sympify( gcdmat))))

<IPython.core.display.Math object>