In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

# NumPy x lists

In [3]:
list_a = [1, 2, 3, 4]

In [5]:
type(list_a)

list

In [6]:
print(id(list_a))

2488681375808


In [7]:
list_a.append(5)
print(list_a)
print(id(list_a))

[1, 2, 3, 4, 5]
2488681375808


In [8]:
array_a = np.array([1,2,3,4])

In [9]:
type(array_a)

numpy.ndarray

In [10]:
print(id(array_a))

2488680430448


In [11]:
array_a = np.append(array_a, 5)
print(array_a)
print(id(array_a))

[1 2 3 4 5]
2488681585552


# Homogeneous

In [15]:
list_a = [1, 2.4, 'a', True, 5]

In [13]:
print(list_a)

[1, 2.4, 'a', True, 5]


In [14]:
type(list_a)


list

In [18]:
for i in list_a:
    print(i)
    print(type(i))

1
<class 'int'>
2.4
<class 'float'>
a
<class 'str'>
True
<class 'bool'>
5
<class 'int'>


In [19]:
array_a = np.array(list_a)
type(array_a)

numpy.ndarray

In [20]:
for i in array_a:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [21]:
array_a.dtype

dtype('<U32')

# Vectorization

In [22]:
list_a = [1,2,3,4]
list_b = [5,6,7,8]

list_c = list_a + list_b
print(list_c)

[1, 2, 3, 4, 5, 6, 7, 8]


In [24]:
list_c = []
for i in range(4):
    list_c.append(list_a[i] + list_b[i])
print(list_c)

[6, 8, 10, 12]


In [25]:
array_a = np.array(list_a)
array_b = np.array(list_b)
array_c = array_a + array_b
print(array_c)

[ 6  8 10 12]


In [26]:
array_a + array_b

array([ 6,  8, 10, 12])

In [27]:
array_a ** array_b

array([    1,    64,  2187, 65536])

# Broadcasting

In [29]:
list_a = [1,2,3,4]
list_a + 5

TypeError: can only concatenate list (not "int") to list

In [30]:
list_b = []
for i in list_a:
    list_b.append(i + 5)
print(list_b)

[6, 7, 8, 9]


In [31]:
array_a = np.array(list_a)
array_a + 5

array([6, 7, 8, 9])

In [32]:
array_b = np.array([[5],
                    [10]])

In [33]:
array_b

array([[ 5],
       [10]])

In [34]:
array_b.shape

(2, 1)

In [35]:
array_a + array_b

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [36]:
array_c = np.array([[5,6],
                    [10,11]])

In [37]:
array_c.shape

(2, 2)