In [1]:
import numpy as np

In [2]:
array_from_list = np.array([1, 2, 3])
array_from_list

array([1, 2, 3])

In [3]:
list_a = [1, 2, 3]
type(list_a)

list

In [4]:
array_from_list = np.array(list_a)
array_from_list

array([1, 2, 3])

In [5]:
type(array_from_list)

numpy.ndarray

In [6]:
tuple_a = (1, 2, 3)
tuple_a

(1, 2, 3)

In [7]:
type(tuple_a)

tuple

In [8]:
array_from_tuple = np.array(tuple_a)
array_from_tuple

array([1, 2, 3])

In [9]:
type(array_from_tuple)

numpy.ndarray

In [10]:
array_from_list + 5

array([6, 7, 8])

In [11]:
array_from_tuple + 5

array([6, 7, 8])

In [12]:
set_a = {1, 2, 3, 4, 4}
print(set_a)
print(type(set_a))

{1, 2, 3, 4}
<class 'set'>


In [13]:
array_from_set = np.array(set_a)
array_from_set

array({1, 2, 3, 4}, dtype=object)

In [14]:
array_from_set + 5

TypeError: unsupported operand type(s) for +: 'set' and 'int'

In [15]:
dict_a = {1: 'a', 2: 'b'}
print(dict_a)
print(type(dict_a))

{1: 'a', 2: 'b'}
<class 'dict'>


In [16]:
array_from_dict = np.array(dict_a)
print(array_from_dict)
print(type(array_from_dict))

{1: 'a', 2: 'b'}
<class 'numpy.ndarray'>


In [17]:
array_from_dict + 5

TypeError: unsupported operand type(s) for +: 'dict' and 'int'