In [1]:
import numpy as np

In [6]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

In [7]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
array_2d[1][1]

np.int64(5)

In [10]:
array_2d[3][2]

np.int64(12)

In [11]:
np.array([[1,2,4],
          [4,5],
          [7,98,9],
          [10]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [17]:
array_3d = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
    ],
    [
        [13,14,15],
        [16,17,18],
        [19,20,21],
        [22,23,24],
    ]
])

In [18]:
array_3d.shape

(2, 4, 3)

In [19]:
array_3d[0][1]

array([4, 5, 6])

### size

In [21]:
list_a = [1,2,3]

In [24]:
array_from_list = np.array(list_a)
array_from_list

array([1, 2, 3])

In [25]:
array_from_list.size

3

In [26]:
len(array_from_list)

3

In [29]:
array_2d # matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
array_2d.size

12

In [30]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [32]:
array_3d.size # show 24 elements

24

### dnim

In [33]:
array_from_list.ndim

1

In [34]:
array_2d.ndim

2

In [35]:
array_3d.ndim

3

### shape

In [38]:
array_from_list.shape # vector

(3,)

In [43]:
array_2d.shape # 4 rows, 3 columns

(4, 3)

In [44]:
array_3d.shape # depths, rows, columns

(2, 4, 3)

### itemsize

In [45]:
array_from_list.itemsize

8

In [46]:
array_2d.itemsize

8

In [47]:
array_3d.itemsize

8

### nbytes

In [50]:
array_from_list.nbytes # amout of memory occupied
# 8 bytes for each element in the array time the 3 ints

24

In [52]:
array_2d.nbytes, 12 * 8

(96, 96)

In [53]:
array_3d.nbytes

192

### dtype

In [54]:
array_from_list.dtype

dtype('int64')

In [55]:
array_2d.dtype

dtype('int64')

In [56]:
array_3d.dtype

dtype('int64')

In [57]:
# each int64 occupies 8 bytes in memory

In [58]:
array_32 = np.array([1,2,3], dtype=np.int32)
array_32.dtype

dtype('int32')

In [59]:
array_32

array([1, 2, 3], dtype=int32)

In [60]:
array_32.itemsize

4