In [2]:
import numpy as np

In [3]:
np.zeros(shape=3)

array([0., 0., 0.])

In [4]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros(shape=(2,3)).dtype

dtype('float64')

In [7]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full(shape=(2,3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4]])

In [11]:
np.empty(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye(N = 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(N = 5, M = 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.identity(n = 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(stop=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(start=3, stop=10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(start=3, stop=10, step=2)

array([3, 5, 7, 9])

In [19]:
np.arange(start=10, stop=3, step=-1)

array([10,  9,  8,  7,  6,  5,  4])

In [21]:
np.linspace(start=1, stop=10, num=4)

array([ 1.,  4.,  7., 10.])

In [22]:
np.linspace(start=1, stop=10, num=7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [23]:
np.logspace(start=1, stop=4, num=4)

array([   10.,   100.,  1000., 10000.])

In [25]:
np.geomspace(start=10, stop=10_000, num=4)

array([   10.,   100.,  1000., 10000.])