In [1]:
import numpy as np

## create a list

In [2]:
list_3d = [
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18],
        [19,20,21],
        [22,23,24]
    ]
]

## convert to numpy

In [3]:
array_3d = np.array(list_3d)

In [4]:
array_3d.shape

(2, 4, 3)

### indexing

In [5]:
array_3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
array_3d[1]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [7]:
array_3d[1][1][2]

np.int64(18)

In [8]:
array_3d[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [14]:
array_3d[:, [0,3]]

array([[[ 1,  2,  3],
        [10, 11, 12]],

       [[13, 14, 15],
        [22, 23, 24]]])

In [15]:
array_3d[-1]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [18]:
array_3d[-1, -2, -1]

np.int64(21)

In [19]:
mask = [True, False]
array_3d[mask]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
mask = array_3d % 2 == 0
mask

array([[[False,  True, False],
        [ True, False,  True],
        [False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True],
        [False,  True, False],
        [ True, False,  True]]])

In [22]:
array_3d[mask]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

### slicing

In [23]:
array_3d[1]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [24]:
array_3d[0:1]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
array_3d[:1]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
array_3d[1]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [27]:
array_3d[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [29]:
array_3d[:, 1:3]

array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[16, 17, 18],
        [19, 20, 21]]])

In [34]:
array_3d[:, :, :2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17],
        [19, 20],
        [22, 23]]])

In [35]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [36]:
array_3d[0, 1:4:2] # this uses the step

array([[ 4,  5,  6],
       [10, 11, 12]])

In [37]:
array_3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
array_3d[0,1::2]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [41]:
array_3d[0,::2] # rows=*, columns=*, step=2

array([[1, 2, 3],
       [7, 8, 9]])

In [42]:
array_3d[0, ::-2]

array([[10, 11, 12],
       [ 4,  5,  6]])

In [44]:
array_3d[0, ::-1]

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

### assigning

In [45]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [48]:
array_3d[1][2][0]

np.int64(19)

In [ ]:
array_3d[1, 2, 0]

np.int64(19)

In [50]:
array_3d[1, 2, 0] = 50

In [51]:
array_3d[1, 2, 0]

np.int64(50)

In [52]:
rng = np.random.default_rng(seed=1)

In [53]:
rng

Generator(PCG64) at 0x2D6390D5EE0

In [54]:
array = rng.normal(loc=50, scale=3, size=60).reshape(3, 5, 4).round(3)

In [55]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])