In [1]:
import numpy as np

In [2]:
np.arange(1, 25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [6]:
array_3d = np.arange(1, 25).reshape(2, 4, 3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

### tolist

In [9]:
# this is just converting back what we did previously
# list_3d = [
#     [
#         [1,2,3],
#         [4,5,6],
#         [7,8,9],
#         [10,11,12]
#     ],
#     [
#         [13,14,15],
#         [16,17,18],
#         [19,20,21],
#         [22,23,24]
#     ]
# ]
# array_3d = np.array(list_3d)
array_3d.tolist()

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]]

In [8]:
type(array_3d.tolist())

list

### item

In [16]:
array_3d[1]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [17]:
array_3d[1, 0]

array([13, 14, 15])

In [18]:
array_3d[1, 0, 2]

np.int64(15)

In [19]:
array_3d.item((1, 0, 2))

15

### view

In [21]:
array_view = array_3d.view()
array_view

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [22]:
array_3d.fill(55)
array_3d

array([[[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]],

       [[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]]])