In [2]:
import numpy as np

In [7]:
arr = np.arange(0,5)

In [8]:
arr

array([0, 1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

### reshape

In [14]:
array_3d = np.arange(1, 25).reshape(2, 3, 4 )

In [15]:
array_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [18]:
# dimensions=2, rows=3, columns=4
array_3d.shape

(2, 3, 4)

In [20]:
# reshape to 4 dimensions with 3 rows and 2 columns
array_3d.reshape(4, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [21]:
# lets reshape to 5 dimensions with 2 rows and 1 column
array_3d.reshape(5, 2, 1)

ValueError: cannot reshape array of size 24 into shape (5,2,1)

### 🙄 WTF!!!

In [24]:
# to diagnose this, look at the size of the array, we have 24 elements
array_3d.size

24

In [27]:
# lets look at what we tried to do. 
# if we multiply the dimensions that we gave (5, 2, 1)
# we get 10, which is not equal to the size of the array (24)
5 * 2 * 1

10

In [29]:
array_3d.reshape(4, 3, -1) # this will autocalculate how many columns that we need, -1 is the majic

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [63]:
array_3d.reshape(4, -1, 2) # this will autocalculate how many rows that we need, but using 2 columns as a restriction

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [50]:
# i have fucked some shit up. I need to get this back to 2 dimensions with 4 rows and 3 columns
array_3d.reshape(2, 4, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

### transpose

In [64]:
array_3d.shape

(4, 3, 2)

In [59]:
arr_transpose = array_3d.transpose((1, 0, 2))
arr_transpose

array([[[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]],

       [[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]],

       [[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]]])

In [60]:
arr_transpose.shape

(3, 4, 2)

we need to look at the original shape of the data
we said 1 as the first argument, what is 1??
if we take the array_3d shape, then 1 is the 3. that means that we want 3 dimensions

![img](../images/array_3dshape_dimensions.png)

I know this is weird, but now we take the second argument, which is 0
what is zero
the zero element of our shape is 4

![img](../images/array_3dshape_rows.png)

now we have 3 dimensions and we wanted to have 4 rows, now lets check out the columns
we specified 2 for the columns argument
2 = the last element, which is ironically 2

![img](../images/array_3d_rows.png)

got 3 dimensions
got 4 rows
got 2 columns


In [61]:
arr_transpose

array([[[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]],

       [[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]],

       [[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]]])

In [62]:
arr_transpose.shape

(3, 4, 2)