In [2]:
import numpy as np

In [3]:
a3d = np.arange(1, 25).reshape(2,4, 3)

In [4]:
a3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [6]:
a3d.take(indices=[1, 5, 10, 12])

array([ 2,  6, 11, 13])

In [7]:
a3d.take(indices=[[1,5], [10,11]])

array([[ 2,  6],
       [11, 12]])

### sort

In [8]:
array_2 = [[10, 3, 7],
           [8, 2, 9]]

In [10]:
array_2.sort()

In [12]:
array_2

[[8, 2, 9], [10, 3, 7]]