In [1]:
import numpy as np

In [4]:
array_2d = np.array([[4,2,12],
                      [10,5,6],
                      [1, 11, 9],
                      [7,8,3]])

### max

In [5]:
array_2d.max(axis=0)

array([10, 11, 12])

In [6]:
array_2d.max(axis=1)

array([12, 10, 11,  8])

### argmax

In [8]:
array_2d.argmax(axis=0) # returns the indexes

array([1, 2, 0])

### argmin

In [12]:
array_2d.argmin(axis=0)

array([2, 0, 3])

### ptp

In [14]:
array_2d

array([[ 4,  2, 12],
       [10,  5,  6],
       [ 1, 11,  9],
       [ 7,  8,  3]])

In [11]:
np.ptp(array_2d, axis=0)  # peak-to-peak (max - min) along the specified axis

array([9, 9, 9])

In [13]:
np.ptp(array_2d, axis=1)

array([10,  5, 10,  5])

### clip

In [19]:
array_2d = np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]])

In [20]:
array_2d.clip(min=3, max=10)

array([[3, 3, 3],
       [4, 5, 6],
       [7, 8, 9]])

### round

In [21]:
array_2d = np.linspace(0, 1, 12).reshape(4, 3)
array_2d

array([[0.        , 0.09090909, 0.18181818],
       [0.27272727, 0.36363636, 0.45454545],
       [0.54545455, 0.63636364, 0.72727273],
       [0.81818182, 0.90909091, 1.        ]])

In [22]:
array_2d.round(decimals=2)

array([[0.  , 0.09, 0.18],
       [0.27, 0.36, 0.45],
       [0.55, 0.64, 0.73],
       [0.82, 0.91, 1.  ]])

### sum

In [23]:
array_2d = np.arange(1, 13).reshape(4, 3)
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
array_2d.sum(axis=0)

array([22, 26, 30])

In [25]:
array_2d.sum(axis=1)

array([ 6, 15, 24, 33])

In [26]:
array_2d.sum()

np.int64(78)

### cumsum

In [27]:
array_2d.cumsum(axis=0)  # cumulative sum along the specified axis

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18],
       [22, 26, 30]])

In [28]:
array_2d.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24],
       [10, 21, 33]])

### mean

In [29]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
array_2d.mean(axis=0)

array([5.5, 6.5, 7.5])

In [31]:
array_2d.mean(axis=1)

array([ 2.,  5.,  8., 11.])

In [32]:
array_2d.mean()

np.float64(6.5)

### var

In [33]:
array_2d.var(axis=0)

array([11.25, 11.25, 11.25])

In [34]:
array_2d.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])

In [35]:
array_2d.var()

np.float64(11.916666666666666)

### std

In [36]:
array_2d.std(axis=0)

array([3.35410197, 3.35410197, 3.35410197])

In [37]:
array_2d.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658, 0.81649658])

In [38]:
array_2d.std()

np.float64(3.452052529534663)

### prod and cumprod

In [39]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
array_2d.prod(axis=0)

array([ 280,  880, 1944])

In [41]:
array_2d.prod(axis=1)

array([   6,  120,  504, 1320])