In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
rng = np.random.default_rng(seed=1)

In [4]:
rng.random()

0.5118216247002567

In [9]:
rng = np.random.default_rng(seed=2)
rng.random()

0.2616121342493164

In [12]:
rng.random(size=10)

array([0.51106597, 0.89120941, 0.77556394, 0.3181466 , 0.9242169 ,
       0.47090989, 0.69375884, 0.10720731, 0.10454356, 0.20190745])

In [13]:
rng.random(size=(5,2))

array([[0.88444967, 0.67981146],
       [0.84923632, 0.64443627],
       [0.4065424 , 0.51657819],
       [0.59344352, 0.86211798],
       [0.43818617, 0.89224011]])

In [14]:
rng.integers(4, size=5)

array([1, 2, 0, 3, 1])

In [15]:
rng.integers(low=10, high=50, size=5)

array([29, 13, 37, 35, 23])

In [16]:
rng.integers(low=10, high=[15, 54, 100])

array([13, 33, 15])

In [17]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
rng.choice(a = array)

np.int64(5)

In [24]:
rng.choice(a = array, size=10)

array([7, 5, 4, 2, 8, 3, 8, 4, 3, 6])

In [26]:
rng.choice(a = array, size=10, replace=False)

array([6, 9, 5, 4, 2, 1, 0, 3, 7, 8])

In [29]:
array = np.array([1,2,3])

In [45]:
p = np.array([0.5, 0.4, 0.1])
rng.choice(a = array, size=10, p=p)

array([1, 2, 3, 3, 3, 1, 2, 1, 1, 1])

In [47]:
array_2d = np.arange(0, 20).reshape(4, 5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
rng.choice(a = array_2d, size=2, axis=0)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [57]:
array = np.arange(10)

In [58]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
rng.shuffle(array)
array

array([2, 9, 0, 7, 8, 4, 6, 1, 3, 5])