In [1]:
import numpy as np

In [2]:
array_1d = np.arange(0, 10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array_2d = np.arange(0, 18).reshape(3, 6)
array_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [5]:
array_2d1 = np.arange(18, 36).reshape(3, 6)
array_2d1

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [6]:
np.concatenate([array_2d, array_2d1])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [7]:
np.concatenate((array_2d, array_2d1), axis=1)

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

In [8]:
array_stacked = np.stack(arrays=[array_2d, array_2d1])
array_stacked

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [9]:
array_stacked.shape

(2, 3, 6)